<?php
//----------------------------------------------------------------------------- 
	//                                    Create the incident 
	//----------------------------------------------------------------------------- 
	function createEvent($subject, $body, $msgNo, $inbox, $db) { 
		$store_number    = ''; 
		$event    = ''; 
		$time = time();
		$status = 'New';
		
		if(strstr($subject, 'PriceNet')) //KSS Email
		{
			$kss = new Kss($body);
			$store_number = $kss->get_site_id();
			$event = shortEvent($kss->get_stage());
		}
		else //Else must be AMCS Email
		{
			$store_number = getStoreFromBody($body);
			$event = shortEvent($subject);
		}

		if($store_number != '' && $event != '' && $body != '')
		{
			$escapeBody = mysqli_real_escape_string($db, $body);
			
			$sql = "INSERT into events values (0, '$store_number','$event', '$time', '$escapeBody')";
			if(!$result = mysqli_query($db, $sql)) {
				do_log('email_functions', 'Cannot add message to events. Wrong DB login Info?', mysqli_real_escape_string($db, $sql), 'Failure', $db);
			}
			else {
				$getId = "SELECT id FROM events WHERE event='$event' AND store_number='$store_number' ORDER BY id DESC LIMIT 1 ";
				//$getId = "SELECT id FROM events WHERE event='$event' AND store_number='$store_number' LIMIT 1 ";
				$resultId = mysqli_query($db, $getId);
				while($ids = mysqli_fetch_array($resultId)) {
					$id = $ids['id'];
				}
				checkProblem($store_number, $event, $body, $id, $db);	
			}
		} 
		else {
				do_log('email_functions', 'Error parsing email. Subject format wrong? Reading body messed up?', '', 'Failure', $db);
		}
		
		if ($result){ /*mark email to delete if the insertion was succesful*/
			$delete = imap_delete($inbox, $msgNo);
		}
	}// end function 
	function getStoreFromBody($body) {
		//Line 1 for store number.
		$lines = preg_split("/(\r\n|\n|\r)/", $body);
		$store = explode(' ', $lines[0]);
		return $store[4];
	}
	function sendMail($subject, $message, $db) {
		$email_from = "AMCSUpdates@p-w-m.com";
		$message .= "\n\nGenerated by AMCS2 Dashboard.\nDo not reply to this email. This is an unmonitored mailbox.";
		
		// create email headers
		$headers = 'From: '.$email_from."\r\n".
		'Reply-To: '.$email_from."\r\n" .
		'X-Mailer: PHP/' . phpversion();
		
		$email_sql = "SELECT email_list FROM system_config LIMIT 1";
		$email_query = mysqli_query($db, $email_sql);
		while($row = mysqli_fetch_array($email_query)) {
			if(!empty($row['email_list'])) {
				$list = explode(' ', $row['email_list']);
				foreach ($list as $email_to) {
					mail($email_to, $subject, $message, $headers);
				}
			}
		}
	}
?>		